### ISSUE TITLE
Bug: Can't download from e-hentai or exhentai

### ISSUE THREAD

**Issue by juh9870** [manga-py/manga-py#178]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 7
Python version | 3.5.2
Pip version | 18.1
Manga-py version | 1.5.4
URL | listed in Additional context

#### Additional context
When trying to download manga from exhentai.org or e-hentai.org in most cases appears error saying `Error processing file: vol_000` with no additional info.
![image](https://user-images.githubusercontent.com/15922601/57180626-477af880-6e93-11e9-8cfa-645e29cfe803.png)

example url that throw this error (i just randomly picked mangas and 8 out of 10 have this problem):
https://exhentai.org/g/1362834/11c07e7453/
https://e-hentai.org/g/1409158/365af0df77/
https://exhentai.org/g/1114716/6de11cbd01/

Example of url that works fine:
https://e-hentai.org/g/1409123/ed8557bd9c/
https://e-hentai.org/g/1409027/efc480a08f/

**Comment by 1271** [comment]
> https://e-hentai.org/g/1409158/365af0df77/

Oh. You have strange tastes :-)
I fixed it. Today will be an update.

> https://exhentai.org/g/1114716/6de11cbd01/ 

in progress now

**Comment by juh9870** [comment]
Oof, i really didnt saw what was inside that first gallery, as i said i was picking random galleries (Second is closer to what i wanted to download).
BTW i ran `pip install --upgrade manga-py`, but error was still there, wasn't this update already uploaded to pypi?

**Comment by 1271** [comment]
Not. There was no release yet. Expect the next hour.

**Comment by juh9870** [comment]
Bug is still there ![image](https://user-images.githubusercontent.com/15922601/57573154-246cbd80-742c-11e9-9eee-9a1230134a80.png)

**Comment by 1271** [comment]
Please, try remove this file:

`C:\Users\<username>\AppData\Roaming\.PyMangaDownloader`

**Comment by juh9870** [comment]
now i cant login back to exhentai, when im entering correct login/passwird pair it requies me to login again, if i enter wrong password it just shows "wrong password" message, it started happpening after i deleted .PyMangaDownloader folder, currently this folder is empty

![image](https://user-images.githubusercontent.com/15922601/57580224-a9e58180-74af-11e9-83cb-29bbea650672.png)

**Comment by 1271** [comment]
Hmmm....
I will check it. Give thanks.
Probably, I was mistaken somewhere :-(

**Comment by 1271** [comment]
I need a little more time for this problem.
Thank you for your patience

**Comment by 1271** [comment]
Ohhh.... Try now, please

**Comment by juh9870** [comment]
Oof
![image](https://user-images.githubusercontent.com/15922601/57634584-4f7f1a80-75ae-11e9-8848-adae45d4a58a.png)

**Comment by 1271** [comment]
Oh! I know what the problem is.
Try to enable vpn for your PC
I mean not a proxy in the browser, but for the whole system (for example openvpn)

Or you can use proxy for manga-py:
https://www.free-proxy-list.net/

You will need a proxy with https
anonymous or elite type

gl =)

---

О! Я знаю в чем проблема.
Попробуйте включить vpn для вашего ПК
Я имею в виду не прокси в браузере, но для всей системы (например openvpn)

Или используйте прокси для manga-py:
https://www.free-proxy-list.net/

Вам нужен https прокси

**Comment by 1271** [comment]
I will need your help a little later.

**Comment by juh9870** [comment]
OOf, is there any way i can view full error log instead of "Error processing file..."

**Comment by 1271** [comment]
Yes. I'll do a test version with debug output this weekend. I need you to install it.
Please wait a bit

**Comment by 1271** [comment]
So...

Please, try download here:
https://github.com/yuru-yuri/manga-dl/archive/stable_1.x.zip

Unzip, go to unzipped files.
And rut it (in your command line):

```bash
python manga.py https://exhentai.org/g/1362834/11c07e7453/
```

You should see the new directory "**manga-py-debug**"
Please pack this and attach to your next answer.

You can do the same with other url addresses.

Debugging works for both sites.

**Comment by juh9870** [comment]
THis version you sent can't download anything at all
![image](https://user-images.githubusercontent.com/15922601/58171176-0c076900-7c9e-11e9-9db2-c5e62a2d7549.png)
And folder manga-py-debug wasn't crerated
![image](https://user-images.githubusercontent.com/15922601/58171200-19bcee80-7c9e-11e9-97c3-7f2d76c40861.png)

**Comment by 1271** [comment]
Hmmmmm
This is really strange

Ok. Please, contact me with discord: https://discord.gg/zjuG9PF

**Comment by 1271** [comment]
I get an error !!! Hooray! 😄

**Comment by 1271** [comment]
Please, check new version

**Comment by 1271** [comment]
Hey. Do you still have problems?

**Comment by juh9870** [comment]
Yep, i'have just cloned this repository and tried to run `python manga.py https://exhentai.org/g/1403504/ff38b6352a/` and got same error as before
![image](https://user-images.githubusercontent.com/15922601/60986589-7bb5de00-a348-11e9-97ae-28be62afeff7.png)

**Comment by 1271** [comment]
It is sad :-(
Have you tried using docker?

**Comment by juh9870** [comment]
Nope, should i try it?

**Comment by 1271** [comment]
Yes if possible

Read here:
https://habr.com/ru/post/358774/#basic - Russian manual
https://docs.docker.com/toolbox/toolbox_install_windows/ - "Docker on Windows Toolbox"

**Comment by juh9870** [comment]
Oof, site is permanently closed now, so there is no longer a point in this issue

**Comment by 1271** [comment]
Anyway. I'm currently working on version 2.0 (not as fast as I would like, but someday it will be ready)
I hope you will have no problems with her if the panda ever returns.
Sorry I could not solve your problem at the moment.

**Comment by 1271** [comment]
Yes. Site down now. Forever
https://knowyourmeme.com/memes/sites/exhentai-sadpanda#fn6

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/68039094-0d6ca100-fcd4-11e9-9fc6-654974e84222.png)
Here we go again...

Description | Data
---|---
OS | Windows 7
Python version | 3.7.3
Pip version | 19.0.1
Manga-py version | 1.9,0
URL | exhentai,org, https://exhentai.org/g/1403504/ff38b6352a/

**Comment by 1271** [comment]
Please, try with option `--debug`

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/68085916-d1118000-fe4e-11e9-8104-0bd04eea2df8.png)

**Comment by juh9870** [comment]
yeah, it works now, thanks!
